version: '3.1'


services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: postgres

  banking-service:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
