global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'banking-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['banking-service:8080']
